"""Tests for target renderers."""

from __future__ import annotations

from pathlib import Path

from basicly import __version__
from basicly.loader import load_fragments_from_roots, load_targets
from basicly.planner import plan_outputs
from basicly.renderers.claude import render as render_claude
from basicly.renderers.common import sha256_of_text
from basicly.schema import Fragment

REPO_ROOT = Path(__file__).parent.parent
FRAGMENT_ROOTS: list[tuple[Path, str | None]] = [
    (REPO_ROOT / ".basicly" / "core" / "fragments", "core"),
    (REPO_ROOT / ".basicly-local" / "fragments", "user"),
]


def test_agents_md_contains_header() -> None:
    """The generated AGENTS.md contains the generated header and expected sections."""
    targets = load_targets(REPO_ROOT / ".basicly" / "core" / "targets")
    target_names = {t.name for t in targets}
    fragments = load_fragments_from_roots(FRAGMENT_ROOTS, target_names)
    planned = plan_outputs(fragments, targets, REPO_ROOT)
    agents = next(p for p in planned if p.output_path == REPO_ROOT / "AGENTS.md")
    content = render_claude(agents, REPO_ROOT / ".basicly" / "core" / "templates", __version__)

    assert "<!-- Generated by basicly" in content
    assert "## Agent Baseline" not in content
    assert "## Core Rules" in content


def test_copilot_plans_no_scoped_instruction_twins() -> None:
    """A path-scoped fragment single-sources to .claude/rules only.

    The copilot target keeps the root baseline but must not plan
    .github/instructions/*.instructions.md twins — VS Code loads both roots
    without dedup, double-loading every path-scoped rule. A synthetic scoped
    fragment exercises the invariant regardless of what the live catalog ships
    (all path-scoped guidance now lives in skills, so the catalog may have none).
    """
    targets = load_targets(REPO_ROOT / ".basicly" / "core" / "targets")
    target_names = {t.name for t in targets}
    fragments = load_fragments_from_roots(FRAGMENT_ROOTS, target_names)
    scoped = Fragment(
        id="scoped-example",
        description="A path-scoped example rule.",
        category="testing",
        applies_to=["all"],
        scope_paths=["**/*.py"],
        body="- rule",
    )
    planned = plan_outputs([*fragments, scoped], targets, REPO_ROOT)

    paths = {p.output_path for p in planned}
    assert REPO_ROOT / ".github" / "copilot-instructions.md" in paths
    assert not [p for p in paths if p.name.endswith(".instructions.md")]
    assert [p for p in paths if p.parent == REPO_ROOT / ".claude" / "rules"]


def test_sha256_of_text() -> None:
    """sha256_of_text returns a stable, prefixed hash."""
    assert sha256_of_text("hello").startswith("sha256:")
    assert sha256_of_text("hello") == sha256_of_text("hello")
    assert sha256_of_text("hello") != sha256_of_text("world")
