from __future__ import annotations

from pathlib import Path

import pytest

from basicly import worktree
from tests import test_worktree_safety
from tests.test_worktree import _git

safety_repo = test_worktree_safety.safety_repo


@pytest.mark.parametrize("contents", ["bytecode", "unexpected", "symlink", "outside", "directory"])
def test_cleanup_recognizes_only_regular_bytecode_in_owned_python_cache(
    safety_repo: Path, contents: str
) -> None:
    session = worktree.create("cache", repo_root=safety_repo)
    cache = session.path / (
        ".cache/__pycache__" if contents == "outside" else ".basicly/core/hooks/__pycache__"
    )
    cache.mkdir(parents=True)
    _git(session.path, "config", "core.excludesFile", str(safety_repo / "cache-ignore"))
    (safety_repo / "cache-ignore").write_text("__pycache__/\n", encoding="utf-8")
    bytecode = cache / "hook.cpython-314.pyc"
    if contents == "symlink":
        bytecode.symlink_to(session.path / "README.md")
    else:
        bytecode.write_bytes(b"generated bytecode")
    if contents == "unexpected":
        (cache / "notes.txt").write_text("retain this", encoding="utf-8")
    if contents == "directory":
        (cache / "nested.pyc").mkdir()
    if contents == "bytecode":
        worktree.cleanup("cache", repo_root=safety_repo)
        assert not session.path.exists()
    else:
        with pytest.raises(SystemExit, match="uncommitted changes"):
            worktree.cleanup("cache", repo_root=safety_repo)
        assert bytecode.is_symlink() if contents == "symlink" else bytecode.exists()
