from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from .projection import SyncResult, sync_file
from .schema import ValidationError, technology_selected

STYLES_SOURCE_DIR = Path(".basicly/core/output-styles")
STYLE_SOURCE_FILE = "style.yaml"
STYLE_FILE_SUFFIX = ".md"
DEFAULT_STYLE_ROOTS = (Path(".claude/output-styles"),)

GENERATED_MARKER = (
    "Generated by `basicly styles-build` from style.yaml. Do not edit; edit the source."
)

UNMANAGED_REASON_PREFIX = "unmanaged ("


@dataclass(frozen=True)
class StyleDefinition:
    slug: str
    name: str
    description: str
    body: str
    keep_coding_instructions: bool = True
    technologies: tuple[str, ...] = ()
    source_path: Path | None = None


def _require_str(value: object, field: str, path: Path) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"{path}: '{field}' must be a non-empty string")
    return value


def load_style(path: Path) -> StyleDefinition:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValidationError(f"{path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ValidationError(f"{path}: an output style source must be a mapping")

    slug = path.parent.name
    name = _require_str(data.get("name"), "name", path)
    description = _require_str(data.get("description"), "description", path)
    body = _require_str(data.get("body"), "body", path)
    keep = data.get("keep_coding_instructions", True)
    if not isinstance(keep, bool):
        raise ValidationError(f"{path}: 'keep_coding_instructions' must be true or false")
    technologies = data.get("technologies") or []
    if not isinstance(technologies, list) or not all(
        isinstance(item, str) for item in technologies
    ):
        raise ValidationError(f"{path}: 'technologies' must be a list of strings")

    return StyleDefinition(
        slug=slug,
        name=name,
        description=description,
        body=body,
        keep_coding_instructions=keep,
        technologies=tuple(technologies),
        source_path=path,
    )


def discover_styles(repo_root: Path, source_dir: Path = STYLES_SOURCE_DIR) -> list[StyleDefinition]:
    root = repo_root / source_dir
    if not root.is_dir():
        return []
    return [
        load_style(path) for path in sorted(root.glob(f"*/{STYLE_SOURCE_FILE}")) if path.is_file()
    ]


def render_style_md(style: StyleDefinition) -> str:
    keep = "true" if style.keep_coding_instructions else "false"
    header = (
        "---\n"
        f"# {GENERATED_MARKER}\n"
        f"name: {style.name}\n"
        f"description: {style.description}\n"
        f"keep-coding-instructions: {keep}\n"
        "---\n"
    )
    return f"{header}\n{style.body}"


def resolve_style_roots(repo_root: Path, roots: list[str] | None) -> list[Path]:
    candidates = [Path(item) for item in roots] if roots else list(DEFAULT_STYLE_ROOTS)
    resolved: list[Path] = []
    seen: set[str] = set()
    for root in candidates:
        absolute = root if root.is_absolute() else repo_root / root
        key = str(absolute)
        if key in seen:
            continue
        seen.add(key)
        resolved.append(absolute)
    return resolved


def _is_generated_style(path: Path) -> bool:
    return path.is_file() and GENERATED_MARKER in path.read_text(encoding="utf-8", errors="ignore")


def _target(root: Path, style: StyleDefinition) -> Path:
    return root / f"{style.slug}{STYLE_FILE_SUFFIX}"


def sync_styles(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = STYLES_SOURCE_DIR,
    selection: frozenset[str] | None = None,
) -> tuple[SyncResult, list[Path]]:
    styles = discover_styles(repo_root, source_dir)
    result = SyncResult()
    pruned: list[Path] = []

    for style in styles:
        selected = technology_selected(list(style.technologies), selection)
        for root in roots:
            target = _target(root, style)
            if selected:
                sync_file(target, render_style_md(style).encode("utf-8"), result)
            elif _is_generated_style(target):
                target.unlink()
                pruned.append(target)

    return result, pruned


def _unmanaged_entries(root: Path, known: set[str], source_dir: Path) -> list[tuple[Path, str]]:
    if not root.is_dir():
        return []
    mismatches: list[tuple[Path, str]] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_file() or entry.suffix != STYLE_FILE_SUFFIX:
            continue
        if entry.stem in known:
            continue
        source = source_dir / entry.stem / STYLE_SOURCE_FILE
        mismatches.append((
            entry,
            f"{UNMANAGED_REASON_PREFIX}no style source at {source.as_posix()})",
        ))
    return mismatches


def check_synced_styles(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = STYLES_SOURCE_DIR,
    selection: frozenset[str] | None = None,
) -> list[tuple[Path, str]]:
    styles = discover_styles(repo_root, source_dir)
    mismatches: list[tuple[Path, str]] = []

    for style in styles:
        selected = technology_selected(list(style.technologies), selection)
        for root in roots:
            target = _target(root, style)
            if not selected:
                if _is_generated_style(target):
                    mismatches.append((target, "excluded by technology selection"))
                continue
            rendered = render_style_md(style).encode("utf-8")
            if not target.exists():
                mismatches.append((target, "missing"))
            elif target.read_bytes() != rendered:
                mismatches.append((target, "content mismatch"))

    known = {style.slug for style in styles}
    for root in roots:
        mismatches.extend(_unmanaged_entries(root, known, source_dir))

    return mismatches
