"""Skill collection discovery and projection helpers.

Skills are authored as a non-discoverable ``skill.yaml`` source (name,
description, ``instructions`` block scalar) so a broadly-scanning agent never
finds the catalog source as a second ``SKILL.md`` (architecture §4.2). The
projector renders the discoverable ``SKILL.md`` at the target roots only, so
exactly one copy an agent can load exists per skill.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from .projection import SyncResult, sync_file
from .schema import ValidationError, technology_selected, validate_technologies

SKILLS_SOURCE_DIR = Path(".basicly/core/skills")
SKILL_SOURCE_FILE = "skill.yaml"
SKILL_FILE_NAME = "SKILL.md"
# .claude/skills is Claude Code's only project root; .agents/skills is the
# Agent Skills open-standard root Codex reads. Copilot/VS Code reads BOTH (plus
# .github/skills), so a .github copy would only triple its discovery — it was
# dropped from the defaults (basicly-sqn) and is pruned as a retired root.
DEFAULT_SKILL_ROOTS = (
    Path(".claude/skills"),
    Path(".agents/skills"),
)

# Roots basicly used to project into; generated-marker files here are pruned on
# skills-build/install and removed by uninstall.
RETIRED_SKILL_ROOTS = (Path(".github/skills"),)

# Marker injected into every rendered SKILL.md so a hand-edit of the projected
# (generated) copy is obviously wrong — the YAML source is the thing to edit.
GENERATED_MARKER = (
    "<!-- Generated by `basicly skills-build` from skill.yaml. Do not edit; edit the source. -->"
)


@dataclass(frozen=True)
class SkillDefinition:
    """A source skill loaded from .basicly/core/skills."""

    slug: str
    name: str
    description: str
    instructions: str
    source_path: Path
    technologies: tuple[str, ...] = ()


def _require_str(value: object, field: str, path: Path) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"missing required field '{field}'", path)
    return value


def discover_skills(
    repo_root: Path,
    source_dir: Path = SKILLS_SOURCE_DIR,
) -> list[SkillDefinition]:
    """Load and validate all skills from the source collection directory."""
    base_dir = repo_root / source_dir
    if not base_dir.exists():
        return []

    skills: list[SkillDefinition] = []
    seen_slugs: set[str] = set()

    for path in sorted(base_dir.glob(f"*/{SKILL_SOURCE_FILE}")):
        slug = path.parent.name
        if slug in seen_slugs:
            raise ValidationError(f"duplicate skill slug '{slug}'", path)
        seen_slugs.add(slug)

        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            raise ValidationError(f"invalid YAML: {exc}", path) from exc
        if not isinstance(data, dict):
            raise ValidationError("skill source must be a YAML mapping", path)

        technologies = validate_technologies(data.get("technologies") or [], path)

        skills.append(
            SkillDefinition(
                slug=slug,
                name=_require_str(data.get("name"), "name", path).strip(),
                description=_require_str(data.get("description"), "description", path).strip(),
                instructions=_require_str(data.get("instructions"), "instructions", path),
                source_path=path,
                technologies=tuple(technologies),
            )
        )

    return skills


def render_skill_md(skill: SkillDefinition) -> str:
    """Render the discoverable SKILL.md (frontmatter + generated marker + body)."""
    header = f"---\nname: {skill.name}\ndescription: {skill.description}\n---\n"
    return f"{header}{GENERATED_MARKER}\n\n{skill.instructions}"


def resolve_skill_roots(
    repo_root: Path,
    roots: list[str] | None,
    use_default_roots: bool,
) -> list[Path]:
    """Resolve output roots for projected skills."""
    if roots:
        candidates = [Path(item) for item in roots]
    elif use_default_roots:
        candidates = list(DEFAULT_SKILL_ROOTS)
    else:
        # Keep default behavior minimal for this repo, but allow expansion with --all-default-roots.
        candidates = [DEFAULT_SKILL_ROOTS[0]]

    resolved: list[Path] = []
    seen: set[str] = set()

    for root in candidates:
        absolute_root = root if root.is_absolute() else repo_root / root
        key = str(absolute_root)
        if key in seen:
            continue
        seen.add(key)
        resolved.append(absolute_root)

    return resolved


def _is_generated_skill(path: Path) -> bool:
    return path.is_file() and GENERATED_MARKER in path.read_text(encoding="utf-8", errors="ignore")


def sync_skills(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = SKILLS_SOURCE_DIR,
    selection: frozenset[str] | None = None,
) -> tuple[SyncResult, list[Path]]:
    """Render selected source skills into destination roots.

    Extra (hand-authored) files are never touched, but a previously projected
    skill the technology *selection* now excludes is pruned (generated-marker
    files only). Returns the sync result plus the pruned paths.
    """
    skills = discover_skills(repo_root, source_dir)
    result = SyncResult()
    pruned: list[Path] = []

    for skill in skills:
        selected = technology_selected(skill.technologies, selection)
        rendered = render_skill_md(skill).encode("utf-8") if selected else b""
        for root in roots:
            target_path = root / skill.slug / SKILL_FILE_NAME
            if selected:
                sync_file(target_path, rendered, result)
            elif _is_generated_skill(target_path):
                target_path.unlink()
                if not any(target_path.parent.iterdir()):
                    target_path.parent.rmdir()
                pruned.append(target_path)

    return result, pruned


def check_synced_skills(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = SKILLS_SOURCE_DIR,
    selection: frozenset[str] | None = None,
) -> list[tuple[Path, str]]:
    """Return missing or stale skill files for the selected destination roots."""
    skills = discover_skills(repo_root, source_dir)
    mismatches: list[tuple[Path, str]] = []

    for skill in skills:
        selected = technology_selected(skill.technologies, selection)
        rendered = render_skill_md(skill).encode("utf-8") if selected else b""
        for root in roots:
            target_path = root / skill.slug / SKILL_FILE_NAME
            if not selected:
                if _is_generated_skill(target_path):
                    mismatches.append((target_path, "excluded by technology selection"))
                continue
            if not target_path.exists():
                mismatches.append((target_path, "missing"))
                continue
            if target_path.read_bytes() != rendered:
                mismatches.append((target_path, "content mismatch"))

    return mismatches
