"""Skill collection discovery and projection helpers.

Skills are authored as a non-discoverable ``skill.yaml`` source (name,
description, ``instructions`` block scalar) so a broadly-scanning agent never
finds the catalog source as a second ``SKILL.md`` (architecture §4.2). The
projector renders the discoverable ``SKILL.md`` at the target roots only, so
exactly one copy an agent can load exists per skill.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from .projection import SyncResult, sync_file
from .schema import ValidationError

SKILLS_SOURCE_DIR = Path(".basicly/core/skills")
SKILL_SOURCE_FILE = "skill.yaml"
SKILL_FILE_NAME = "SKILL.md"
DEFAULT_SKILL_ROOTS = (
    Path(".claude/skills"),
    Path(".github/skills"),
    Path(".agents/skills"),
)

# Marker injected into every rendered SKILL.md so a hand-edit of the projected
# (generated) copy is obviously wrong — the YAML source is the thing to edit.
GENERATED_MARKER = (
    "<!-- Generated by `basicly skills-build` from skill.yaml. Do not edit; edit the source. -->"
)


@dataclass(frozen=True)
class SkillDefinition:
    """A source skill loaded from .basicly/core/skills."""

    slug: str
    name: str
    description: str
    instructions: str
    source_path: Path


def _require_str(value: object, field: str, path: Path) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValidationError(f"missing required field '{field}'", path)
    return value


def discover_skills(
    repo_root: Path,
    source_dir: Path = SKILLS_SOURCE_DIR,
) -> list[SkillDefinition]:
    """Load and validate all skills from the source collection directory."""
    base_dir = repo_root / source_dir
    if not base_dir.exists():
        return []

    skills: list[SkillDefinition] = []
    seen_slugs: set[str] = set()

    for path in sorted(base_dir.glob(f"*/{SKILL_SOURCE_FILE}")):
        slug = path.parent.name
        if slug in seen_slugs:
            raise ValidationError(f"duplicate skill slug '{slug}'", path)
        seen_slugs.add(slug)

        try:
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as exc:
            raise ValidationError(f"invalid YAML: {exc}", path) from exc
        if not isinstance(data, dict):
            raise ValidationError("skill source must be a YAML mapping", path)

        skills.append(
            SkillDefinition(
                slug=slug,
                name=_require_str(data.get("name"), "name", path).strip(),
                description=_require_str(data.get("description"), "description", path).strip(),
                instructions=_require_str(data.get("instructions"), "instructions", path),
                source_path=path,
            )
        )

    return skills


def render_skill_md(skill: SkillDefinition) -> str:
    """Render the discoverable SKILL.md (frontmatter + generated marker + body)."""
    header = f"---\nname: {skill.name}\ndescription: {skill.description}\n---\n"
    return f"{header}{GENERATED_MARKER}\n\n{skill.instructions}"


def resolve_skill_roots(
    repo_root: Path,
    roots: list[str] | None,
    use_default_roots: bool,
) -> list[Path]:
    """Resolve output roots for projected skills."""
    if roots:
        candidates = [Path(item) for item in roots]
    elif use_default_roots:
        candidates = list(DEFAULT_SKILL_ROOTS)
    else:
        # Keep default behavior minimal for this repo, but allow expansion with --all-default-roots.
        candidates = [DEFAULT_SKILL_ROOTS[0]]

    resolved: list[Path] = []
    seen: set[str] = set()

    for root in candidates:
        absolute_root = root if root.is_absolute() else repo_root / root
        key = str(absolute_root)
        if key in seen:
            continue
        seen.add(key)
        resolved.append(absolute_root)

    return resolved


def sync_skills(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = SKILLS_SOURCE_DIR,
) -> SyncResult:
    """Render source skills into destination roots without deleting extra files."""
    skills = discover_skills(repo_root, source_dir)
    result = SyncResult()

    for skill in skills:
        rendered = render_skill_md(skill).encode("utf-8")
        for root in roots:
            sync_file(root / skill.slug / SKILL_FILE_NAME, rendered, result)

    return result


def check_synced_skills(
    repo_root: Path,
    roots: list[Path],
    source_dir: Path = SKILLS_SOURCE_DIR,
) -> list[tuple[Path, str]]:
    """Return missing or stale skill files for the selected destination roots."""
    skills = discover_skills(repo_root, source_dir)
    mismatches: list[tuple[Path, str]] = []

    for skill in skills:
        rendered = render_skill_md(skill).encode("utf-8")
        for root in roots:
            target_path = root / skill.slug / SKILL_FILE_NAME
            if not target_path.exists():
                mismatches.append((target_path, "missing"))
                continue
            if target_path.read_bytes() != rendered:
                mismatches.append((target_path, "content mismatch"))

    return mismatches
