from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

if TYPE_CHECKING:
    from basicly.schema import PlannedOutput


def make_env(templates_dir: Path) -> Environment:
    return Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=False,  # noqa: S701 — non-HTML output; see the note above
        keep_trailing_newline=True,
    )


def generated_header(version: str) -> str:
    return f"<!-- Generated by basicly v{version}. Do not edit manually. -->\n"


def render_output(env: Environment, planned: PlannedOutput, version: str) -> str:
    template = env.get_template(planned.template)
    content = template.render(
        fragments=planned.fragments,
        header=generated_header(version),
        target_name=planned.target_name,
        output_name=planned.output_name,
    )
    return content.rstrip() + "\n"


def sha256_of_text(text: str) -> str:
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
