"""Shared rendering helpers."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TYPE_CHECKING

from jinja2 import Environment, FileSystemLoader

if TYPE_CHECKING:
    from basicly.schema import PlannedOutput


def make_env(templates_dir: Path) -> Environment:
    """Create a Jinja2 environment for templates under templates_dir."""
    return Environment(
        loader=FileSystemLoader(str(templates_dir)),
        # These templates render Markdown and TOML instruction files, never HTML, and the
        # output is read by an agent and by git. The alternative — `select_autoescape` —
        # was rejected because autoescaping turns a literal `&` or `<` in a fragment body
        # into an entity in the projected file, i.e. corrupts every generated artifact.
        # The XSS sink the rule guards does not exist: nothing here is served to a browser.
        autoescape=False,  # noqa: S701 — non-HTML output; see the note above
        keep_trailing_newline=True,
    )


def generated_header(version: str) -> str:
    """Return the standard generated-file HTML comment header."""
    return f"<!-- Generated by basicly v{version}. Do not edit manually. -->\n"


def render_output(env: Environment, planned: PlannedOutput, version: str) -> str:
    """Render a planned output using its target template."""
    template = env.get_template(planned.template)
    content = template.render(
        fragments=planned.fragments,
        header=generated_header(version),
        target_name=planned.target_name,
        output_name=planned.output_name,
    )
    return content.rstrip() + "\n"


def sha256_of_text(text: str) -> str:
    """Return a sha256:... hash of the given text."""
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()
