"""Which comments a strip must leave behind, because a tool reads them.

A comment is a directive when removing it changes what some other program does. That is
the whole test, and it is why this list is not a matter of taste: strip `# noqa` and the
linter fails; strip `// @ts-expect-error` and the compiler fails; strip a shebang and the
file stops being executable.

Measured over this repository on 2026-09-12: 332 of the 10258 `#` comments in the tracked
Python tree are directives - `noqa` 122, `nosec` 108, `type: ignore` 48,
`comment-density-waiver:` 25, `pragma: no` 14, `module-size-waiver:` 10, shebang 2 and
`fmt:` 3. The rest of the table covers the other languages the kit claims, so a consumer
does not discover the gap by having their build broken.

Two entries are here for a reason other than tooling. `SPDX-License-Identifier` and a
`/*!` banner carry licence text, and deleting someone's licence notice is not a
formatting decision this kit gets to make.
"""

from __future__ import annotations

import re

_PATTERNS = (
    r"noqa\b",
    r"nosec\b",
    r"nolint\b",
    r"nosonar\b",
    r"type:\s*ignore",
    r"pragma:",
    r"pylint:",
    r"flake8:",
    r"mypy:",
    r"pyright:",
    r"ruff:",
    r"bandit:",
    r"vulture:",
    r"isort:",
    r"nopycln",
    r"fmt:\s*(?:on|off|skip)",
    r"yapf:\s*(?:disable|enable)",
    r"coding[:=]",
    r"-\*-",
    r"[a-z][a-z0-9-]*-waiver:",
    r"shellcheck\b",
    r"eslint-disable",
    r"eslint-enable",
    r"eslint-env",
    r"globals\b",
    r"prettier-ignore",
    r"biome-ignore",
    r"oxlint-disable",
    r"stylelint-disable",
    r"stylelint-enable",
    r"@ts-ignore",
    r"@ts-expect-error",
    r"@ts-nocheck",
    r"@jsx\b",
    r"@jsxImportSource",
    r"@flow\b",
    r"istanbul\s+ignore",
    r"[cv]8\s+ignore",
    r"webpack[A-Za-z]+:",
    r"sourceMappingURL=",
    r"sourceURL=",
    r"go:[a-z]+",
    r"CHECKSTYLE:",
    r"ReSharper\s+(?:disable|restore)",
    r"<auto-generated",
    r"SPDX-[A-Za-z-]+:",
    r"\[if\s",
    r"\[endif\]",
)

_DIRECTIVE = re.compile(
    r"^(?:{})".format("|".join(_PATTERNS)),
    re.IGNORECASE,
)

_OPENERS = ("#!", "#", "//", "/*", "<!--", "<#", "--", "'")


def body(text: str) -> str:
    """*text* with its comment opener and surrounding whitespace removed."""
    stripped = text.strip()
    for opener in _OPENERS:
        if stripped.startswith(opener):
            return stripped[len(opener) :].strip()
    return stripped


def is_directive(text: str) -> bool:
    """True where *text* is a comment some tool reads, so a strip must keep it.

    Two forms are answered before the table, because in each the opener is the whole
    directive and a pattern for it would also match prose: a shebang, and the `/*!`
    banner every minifier preserves because it holds a licence.
    """
    lead = text.lstrip()
    if lead.startswith(("#!", "/*!", "//!")):
        return True
    return bool(_DIRECTIVE.match(body(text)))
