"""Tests for the protect-generated Claude Code PreToolUse guard."""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

SCRIPT_PATH = (
    Path(__file__).resolve().parents[2] / ".basicly" / "core" / "hooks" / "protect-generated.py"
)

FRAGMENT_MARKER = "<!-- Generated by basicly v0.1.2. Do not edit manually. -->\n"
SKILL_MARKER = (
    "<!-- Generated by `basicly skills-build` from skill.yaml. Do not edit; edit the source. -->\n"
)


def _load_module():
    spec = importlib.util.spec_from_file_location("protect_generated_hook", SCRIPT_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_hook(payload: object) -> subprocess.CompletedProcess[str]:
    stdin = payload if isinstance(payload, str) else json.dumps(payload)
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH)],
        input=stdin,
        capture_output=True,
        text=True,
        check=False,
    )


def test_detects_fragment_and_skill_markers(tmp_path: Path) -> None:
    """Both marker flavors are recognized, wherever they sit in the opening lines."""
    module = _load_module()

    direct = tmp_path / "CLAUDE.md"
    direct.write_text(FRAGMENT_MARKER + "# Rules\n", encoding="utf-8")
    assert module.is_generated(direct)

    after_frontmatter = tmp_path / "SKILL.md"
    after_frontmatter.write_text(
        "---\nname: demo\ndescription: d\n---\n" + SKILL_MARKER + "# Demo\n", encoding="utf-8"
    )
    assert module.is_generated(after_frontmatter)


def test_manifest_json_counts_as_generated(tmp_path: Path) -> None:
    """The marker-less projection manifest is matched by its constant basename."""
    module = _load_module()
    manifest = tmp_path / "generated-manifest.json"
    manifest.write_text("{}\n", encoding="utf-8")
    assert module.is_generated(manifest)


def test_normal_files_are_not_generated(tmp_path: Path) -> None:
    """A plain source file, even one that merely mentions basicly, passes."""
    module = _load_module()
    source = tmp_path / "notes.md"
    source.write_text("# Notes\n\nbasicly is a projector.\n", encoding="utf-8")
    assert not module.is_generated(source)


def test_blocks_edit_of_generated_file(tmp_path: Path) -> None:
    """An Edit targeting a marker file exits 2 and names the source workflow."""
    target = tmp_path / "AGENTS.md"
    target.write_text(FRAGMENT_MARKER + "# Baseline\n", encoding="utf-8")

    proc = _run_hook({"tool_name": "Edit", "tool_input": {"file_path": str(target)}})
    assert proc.returncode == 2
    assert "basicly build" in proc.stderr


def test_allows_edit_of_normal_file(tmp_path: Path) -> None:
    """A normal file passes with no output."""
    target = tmp_path / "main.py"
    target.write_text("print('hi')\n", encoding="utf-8")

    proc = _run_hook({"tool_name": "Edit", "tool_input": {"file_path": str(target)}})
    assert proc.returncode == 0


def test_fails_open_on_missing_file_and_bad_payloads(tmp_path: Path) -> None:
    """Nonexistent targets, absent paths, and garbage stdin never block."""
    missing = {"tool_name": "Write", "tool_input": {"file_path": str(tmp_path / "new.md")}}
    assert _run_hook(missing).returncode == 0
    assert _run_hook({"tool_name": "Edit", "tool_input": {}}).returncode == 0
    assert _run_hook("not json at all").returncode == 0
